api/urls.py
from rest_framework.routers import DefaultRouter

from api.views import BuyerViewSet, PanViewSet

router = DefaultRouter()
router.register("buyers", BuyerViewSet)
router.register("pans", PanViewSet)

urlpatterns = []

urlpatterns.extend(router.urls)

web/urls.py
from django.urls import path
from .views import PanCreateView, PanUpdateView, PanDeleteView, profile_view, RegisterView, index, WebPasswordResetView, \
    register_confirm

app_name = "web"

urlpatterns = [
    path('', index, name="index"),
    path('pans', PanCreateView.as_view(), name="create_pan"),
    path('pans/<pk>', PanUpdateView.as_view(), name="update_pan"),
    path('pans/<pk>/delete', PanDeleteView.as_view(), name="delete_pan"),
    path('profile', profile_view, name="profile"),
    path('register', RegisterView.as_view(), name="register"),
    path("password_reset/", WebPasswordResetView.as_view(), name="password_reset"),
    path("register_confirm/<token>/", register_confirm, name="register_confirm"),
]

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Youtube project</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
{%  block body %}
{% endblock %}
</body>
</html>

web/templates/web/index.html
{%  extends 'web/base.html' %}
{% load i18n %}

{%  block body %}

        <div class="card" style="width: 30%; margin: 10% auto auto;">
        <div class="card-body" style="background-color: #2aabd2; border-color: #1A01CC">
            <div class="row" >
                <div class="col">
                    <button onclick="document.location.href='{% url "web:profile" %}'">{% translate 'Profile' %}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/web/password_reset_email.html
{% extends 'web/base.html' %}

{%  block body %}
    <h1>СБРОС ПАРОЛЯ</h1>
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SUBMIT</button>
    </form>

{% endblock %}

web/templates/web/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Profile</title>
</head>
<body>
    <div class="container mt-5 d-flex justify-content-center">

                <div class="card p-3">

                    <div class="d-flex align-items-center">

                        <div class="image">
                    <img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="rounded" width="155" >
                    </div>

                    <div class="ml-3 w-100">

                       <h4 class="mb-0 mt-0">{{ user.username }}</h4>
                       <span>Опытный журналист</span>

                       <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">

                        <div class="d-flex flex-column">

                            <span class="articles">Статьи</span>
                            <span class="number1">38</span>

                        </div>

                        <div class="d-flex flex-column">

                            <span class="followers">Followers</span>
                            <span class="number2">980</span>

                        </div>


                        <div class="d-flex flex-column">

                            <span class="rating">Rating</span>
                            <span class="number3">8.9</span>

                        </div>

                       </div>


                       <div class="button mt-2 d-flex flex-row align-items-center">

                        <button class="btn btn-sm btn-outline-primary w-100" onclick="location.href='{% url 'password_change' %}'">Change password</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'logout' %}?next={% url 'web:index' %}'">Logout</button>


                       </div>


                    </div>


                    </div>

                </div>

             </div>
</body>
</html>